### PR TITLE
Adding Algeria Map

### PR DESCRIPTION
**Pull request by medkhelifi**
Hi;
I Added Algeria map with its Departments, Thank you to accept this pull request...

### CODE REVIEW

**Comment by WassiMan** [comment]
@medkhelifi Great to hear that, we need it at work :-)

**Comment by Indigo744** [comment]
Thanks for the PR! Can you provide a JSFiddle presenting the map? Thanks :)

**Comment by medkhelifi** [comment]
Here we go ...
https://jsfiddle.net/medkhelifi/df1L2wqL/

**Comment by medkhelifi** [comment]
Here we go:
https://jsfiddle.net/medkhelifi/df1L2wqL/1/

**Comment by Indigo744** [comment]
Thanks a lot. The quality looks good :)

I have however some questions:
- What is the projection? Equirectangular? Can you specify it in comment header?
- From which SVG file did you create this map? Can you attribute the source?
- You didn't defined any `getCoords()` function. Can you define one, even if empty (returning directly lon, lat)

**Comment by medkhelifi** [comment]
1- I don't understand this question ??!!!
2- I create my svg file from this website: https://pixelmap.amcharts.com/
3- I defined getCoords(), I will make another pull request, but I'm not sure if the data are accurate.
4- DZ is the coutry code for Algeria, but I can give the name of departments.

**Comment by Indigo744** [comment]
Well, a map projection represents the method of transforming the spherical world into a flat surface (hence, you are projecting the real point to an approximation). See https://en.wikipedia.org/wiki/Map_projection.

In the website AMCharts, you can define the projection in the first box on the left.
It looks like you used the Mercator projection (a classic one). However, this projection uses complex coordination transformation from longitude,latitude to x,y.

Regarding the naming, I think this is OK like this :)

**Comment by medkhelifi** [comment]
I finished the naming of departments, and added getCoords() function.

Thank you :)

**Comment by Indigo744** [comment]
Can you add the source (something along `generated from https://pixelmap.amcharts.com`) in your comments?

The `getCoords` function seems to correspond to an Equirectangular projection. Either generate your SVG from this projection, or implements the Mercator projection. You have to be consistent!

**Comment by medkhelifi** [comment]
I recreated another Equirectangular projection svg map with the correspondent coordinates.
I also added the svg source file.

**Comment by Indigo744** [comment]
Really good! 

Now if you can just delete the SVG file, I will merge your PR ;-)

**Comment by medkhelifi** [comment]
Done SVG File deleted ...

**Comment by neveldo** [comment]
Thanks a lot @medkhelifi for this great new map !! @Indigo744 will merge it to the master branch as all seems to be ok now :)

**Comment by Indigo744** [comment]
Thanks @medkhelifi for your contribution :)

**Comment by medkhelifi** [comment]
pleased to contribute to this api, I find it very useful :)

**Pull request merged**
