### PR TITLE
Add Canada Map (uses Lambert Conformal Conic Projection)

### PR DESCRIPTION
**Pull request by Cabalist**
This is not the cleanest code but it does work and it is 'correct' map wise.  If someone else with more JS skills cleans it up I think it is a good addition.

It looks like this:

image

instead of this:

image

### CODE REVIEW

**Comment by Indigo744** [comment]
Can you tell me which source you used for the SVG/coordinate computation?

**Comment by Indigo744** [comment]
I think I'm done with the cleaning.

You can see your map in action (with some plots to check getCoords) here: https://jsfiddle.net/084z3ssg/2/

I'm just waiting @Cabalist information on potential sources for SVG/computation and we can merge.

**Comment by Cabalist** [comment]
SVG data came from the Wikicommons map of Canada.

Computation were written in house by an employee.  Based off math from a number of places.

**Comment by Indigo744** [comment]
Do you want us to cite your company?

**Comment by Cabalist** [comment]
Nah that is alright.  Cabalist or Ryan Jarvis works great.  :)

**Comment by Indigo744** [comment]
Ok :) merging!

**Comment by Cabalist** [comment]
Thanks for your effort here. :)

**Comment by neveldo** [comment]
Thank you  both @Cabalist @Indigo744  for this new map !

**Pull request merged**
