### PR TITLE
Map of the uk with postal zones

### PR DESCRIPTION
**Pull request by Coursmayeur**
Hello,

Here's the map of the uk divided by postcode areas. JSfiddle [here](https://jsfiddle.net/Coursmayeur/ss15eLr0/) and the souce for the division is [here](https://upload.wikimedia.org/wikipedia/commons/f/fe/British_postcode_areas_map.svg)

### CODE REVIEW

**Comment by neveldo** [comment]
Hello @Coursmayeur ,

Many thanks for your contribution !

Could you set the author and the URL to the source map into the comment at the top of the JS file ?
Moreover, it seems that you didn't preserve the original aspect ratio of the map (the overall shape of the country seems to be wider as in the original one). Is it desired ?

**Comment by Coursmayeur** [comment]
Hello @neveldo 
I followed [this](https://github.com/roblascelles/uk-postcode-map/wiki/Cobbling-together-UK-postcode-area-data) to get a svg and then used your tool svg to mapael. So if you're referring to the wiki link when you talk about the different looking shapes, it's normal. The wiki only justifies the labelling I used.

Which author and URL should I specify then, as there is not any actual source ?

**Comment by neveldo** [comment]
Thanks, I got it, I thought your map was based on the wikipedia one ( https://commons.wikimedia.org/wiki/File:British_postcode_areas_map.svg ).

For the author, since it's you, you can set your github pseudonym or your firstname / lastname as you wish :)

**Comment by Coursmayeur** [comment]
It should be better now.
I also added the same map but with the Pseudo-Mercator projection (EPSG 3857), it is better looking I think !

**Comment by Coursmayeur** [comment]
Hello @neveldo 
Yes, I said in my last post that the projections are different. The ids are the same indeed, but content is not the same.

**Comment by neveldo** [comment]
Oh sorry, It seems that I'm a little bit tired ! 

So a very little mistake remains in the mercator one : you left the default map name in the top comment : `Map of your_map_name`. After that, I will be able to merge it to the repository !

Many thanks !

**Comment by neveldo** [comment]
Hello @Coursmayeur , 

Thank you for having updated your pull request. 

And, of course, thank a lot for your contribution to the repository !!

**Pull request merged**
