### PR TITLE
Added maps

### PR DESCRIPTION
**Pull request by IsmaCadenas**

### CODE REVIEW

**Comment by neveldo** [comment]
Hi @IsmaCadenas , thanks again for your new contribution, and sorry for my late review. All seems to be good except for China map that don't seems to display. The SVG paths data seems to be wrong compared to the overall size of the map : 

```
(...)7 3-1.2 1.9 1 0.9 7.5 3.5 2.7 3.1-1 0.9-0.9 0.2-0.9-0.1-1 0.2-0.8 0.7-0.6(....)
```
Could you take a look ?

**Comment by IsmaCadenas** [comment]
I update the files. I see the map OK, Could you try it?

**Comment by neveldo** [comment]
It seems to be ok now, thanks again for your contribution to the maps !

**Comment by neveldo** [comment]
(I think that the first time I was trying the map of China using a wrong ID ('china' instead of 'cn'))

**Pull request merged**
