### PR TITLE
Create trinidad_and_tobago.js

### PR DESCRIPTION
**Pull request by chineyting**
Trinidad and Tobago showing electoral districts

### CODE REVIEW

**Comment by Indigo744** [comment]
Nice! Do you have a working example, by any chance?

**Comment by chineyting** [comment]
:). [http://www.looptt.com/content/election-results](url)

**Comment by chineyting** [comment]
And here's a screenshot.

image

**Comment by Indigo744** [comment]
I see a lot of "hole" in the map. Is that normal? Why the lines don't match?

**Comment by chineyting** [comment]
Ikr. I think it was due to the original map image that I received.

**Comment by Indigo744** [comment]
I'm merging this PR. I will update the file to be compliant with Mapael 2.x

**Pull request merged**
