### PR TITLE
Add world country with antarctica

### PR DESCRIPTION
**Pull request by Indigo744**
Add equirectangular world map with Antarctica shown.
Extend from -180° to 180° longitude and -90 to 90° latitude

See: https://jsfiddle.net/03rvhaew/1/

Fix neveldo/jQuery-Mapael/issues/308

### CODE REVIEW

**Comment by neveldo** [comment]
Hello @Indigo744 ,

Thanks for this new map ! Not a big concern yet, but I think we should consider later to identify the countries with their ISO codes (for instance).

**Comment by Indigo744** [comment]
You are right, but unfortunately the source file (https://commons.wikimedia.org/wiki/File:World_location_map.svg) had these value in French.
Maybe I could update it through a script...

**Comment by neveldo** [comment]
It could be great if you can do so, but don't worry, I think it's still a
great first version for the map even with the french state names as IDs
(that's why I approved it).

**Comment by Indigo744** [comment]
Done :)

**Comment by neveldo** [comment]
Wow, you updated it quickly, it's ok for me !

**Pull request merged**
