### PR TITLE
Added India + basic states (no union territories except Goa, Andaman/…

### PR DESCRIPTION
**Pull request by BlaidddDrwg**
…Nicobar islands, Delhi, and Lakshadweep). In short, this map is detailed enough for most purposes, but not comprehensive as a source for geographically accurate information.

### CODE REVIEW

**Comment by neveldo** [comment]
Hello,

Thanks for your contribution ! Your map seems to be ok except for one point : this is the old map format (for mapael 1.*), you now get this warning if you use it with mapael 2;* : "Extending $.fn.mapael is deprecated".

In order to fix this, you just have to take as base map a random map on this repository, and replace the 'map' object with the one in your map. Don't forget to update also the head comment.

Thanks !

**Comment by BlaidddDrwg** [comment]
Hi, have committed a modified map, based upon the template from Germany.  I am unable to test, since what I'm using is using Mapael 1, so let me know if there's a way to test the map in a neutral environment.

**Comment by neveldo** [comment]
Hi,

Sorry for my late answer and thanks again ! It's almost perfect, you just missed to replace one line, l24 :
```
    $.extend(true, $.fn.mapael,
```

Should be replaced by 

```
    $.extend(true, Mapael,
```

**Comment by BlaidddDrwg** [comment]
Hi, done.. Many thanks for your review.
I should really set up something at my end to test this with Mapael2 !

**Comment by neveldo** [comment]
Hello @BlaidddDrwg ,

Thanks a lot ! It's ok now, I merge your pull request to the repository !

Thanks again !

**Pull request merged**
