### PR TITLE
implemented getCoords for germany map

### PR DESCRIPTION
**Pull request by xat**

### CODE REVIEW

**Comment by neveldo** [comment]
Hi @xat ,

Happy new year and many thanks for your contribution !

However, I have checked the getCoords() function, and it seems that when I plot a city, it is displayed somewhere at south-east from the real position of the city. Maybe you have done an improved version since ?

**Comment by Indigo744** [comment]
@xat any update on it?

**Comment by Indigo744** [comment]
I checked, and as @neveldo said, there seems to be an issue with the computation: https://jsfiddle.net/z1o91cys/1/

See, Berlin and Zittau are not properly placed. I think there is an issue regarding the longitude computation.

**Comment by Indigo744** [comment]
I recomputed the getCoords() function and I got:
```js
            var xfactor = 64.231908437415,
              xoffset = -377.90181740496,
              x = (lon * xfactor) + xoffset,
              yfactor = -102.05323203605,
              yoffset = 5617.9125521016,
              y = (lat * yfactor) + yoffset;
```
See here: https://jsfiddle.net/z1o91cys/3/

If you don't have time to update your file, I'll merge and modify it directly.

**Comment by neveldo** [comment]
Great work @Indigo744 !

**Pull request merged**
