### PR TITLE
Map of Trinidad and Tobago

### PR DESCRIPTION
**Pull request by chineyting**
Map showing electoral districts of Trinidad and Tobago.

### CODE REVIEW

**Comment by Indigo744** [comment]
Hello @chineyting
Your PR is not showing any file change. 
This seems to be due to the "revert" command you did.

**Comment by chineyting** [comment]
Hi,
There wasn't any actual change to the file.
The revert can be ignored.

Hello @chineyting <https://github.com/chineyting>
Your PR is not showing any file change.
This seems to be due to the "revert" command you did.

—
Reply to this email directly or view it on GitHub
<https://github.com/neveldo/mapael-maps/pull/20#issuecomment-186178012>.

**Comment by Indigo744** [comment]
But still! This PR shows *no* modification to the repo (see tabs "0 files changed"). 
Hence, if we merge it, it will do nothing.

Can you clean your branch? Thanks!

**Comment by Indigo744** [comment]
I'm closing this PR :)

**Pull request closed without merging**
